import Link from "next/link";
import { listMockAssetCleanupPolicies } from "@chainvigil/risk-core";
import { MobileNav } from "../../ui/mobile-nav";

export default function DustPage() {
  const policy = listMockAssetCleanupPolicies().find((item) => item.flow === "dust_scan");
  if (!policy) return null;

  return <main className="min-h-screen bg-[#0a0b0f] pb-24 text-[#e4e1ed] md:pb-10"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#262932] bg-[#0a0b0f]/95 px-5 backdrop-blur md:px-8"><Link href="/" className="font-semibold text-[#f9fafb]">ChainVigil AI</Link><Link href="/app/asset-barber" className="text-sm text-[#c7c4d7]">资产理发师</Link></header><div className="mx-auto max-w-6xl px-5 py-9 md:px-8"><section><p className="text-sm font-semibold text-[#c0c1ff]">Read-only policy</p><h1 className="mt-3 text-3xl font-semibold text-[#f9fafb] md:text-5xl">粉尘扫描</h1><p className="mt-4 max-w-2xl leading-7 text-[#9ca3af]">评估低价值资产是否值得处理。V0/V1 不执行粉尘归集、自动 swap 或跨链 bridge。</p></section><section className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><p className="text-sm text-[#9ca3af]">扫描状态</p><p className="mt-3 text-xl font-semibold text-[#f59e0b]">等待只读地址分析</p></article><article className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><p className="text-sm text-[#9ca3af]">处理策略</p><p className="mt-3 text-xl font-semibold text-[#c0c1ff]">人工复查</p></article><article className="rounded-xl border border-[#ef4444]/30 bg-[#16181d] p-5"><p className="text-sm text-[#9ca3af]">执行能力</p><p className="mt-3 text-xl font-semibold text-[#ef4444]">V0 未开放</p></article></section><section className="mt-8 rounded-xl border border-[#262932] bg-[#16181d] p-6"><h2 className="text-2xl font-semibold text-[#f9fafb]">{policy.title}</h2><p className="mt-4 max-w-3xl leading-7 text-[#c7c4d7]">{policy.description}</p><div className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-lg bg-[#1b1b23] p-5"><h3 className="font-semibold text-[#c0c1ff]">进入候选前必须检查</h3><div className="mt-4 flex flex-wrap gap-2">{policy.requiredChecks.map((check) => <span key={check} className="rounded bg-[#292932] px-3 py-2 text-sm text-[#c7c4d7]">{check}</span>)}</div></div><div className="rounded-lg border border-[#ef4444]/25 bg-[#ef4444]/5 p-5"><h3 className="font-semibold text-[#ef4444]">禁止动作</h3><div className="mt-4 flex flex-wrap gap-2">{policy.prohibitedActions.map((action) => <span key={action} className="rounded border border-[#ef4444]/25 px-3 py-2 text-sm text-[#c7c4d7]">{action}</span>)}</div></div></div></section><section className="mt-8 rounded-xl border border-[#262932] bg-[#1b1b23] p-6"><h2 className="text-xl font-semibold text-[#f9fafb]">为什么粉尘也要谨慎</h2><p className="mt-3 leading-7 text-[#9ca3af]">低价值不代表低风险。未知资产可能携带钓鱼链接或恶意合约，任何处理都应由用户在确认成本、风险和交易内容后自行决定。</p></section></div><MobileNav active="wallet" /></main>;
}
