import Link from "next/link";
import { getMockPointLedgerSummary, listPointRules } from "@chainvigil/points";
import { MobileNav } from "../../ui/mobile-nav";

export default function PointsPage() {
  const rules = Object.entries(listPointRules());
  const ledger = getMockPointLedgerSummary();

  return <main className="min-h-screen bg-[#0a0b0f] px-4 py-6 pb-28 md:px-8"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between border-b border-[#262932] text-sm text-[#9ca3af]"><Link href="/" className="font-semibold text-[#f9fafb]">ChainVigil AI｜链哨 AI</Link><Link href="/app">App 控制台</Link></nav><section className="mx-auto mt-8 flex max-w-7xl flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#eab308]">Vigil Points</p><h1 className="mt-2 text-3xl font-semibold text-[#f9fafb]">哨点 VP</h1><p className="mt-3 text-sm text-[#c7c4d7]">记录真实产品使用、安全贡献和推广贡献。</p></div><p className="rounded-xl border border-[#262932] bg-[#16181d] px-4 py-3 text-sm text-[#9ca3af]">待确认 <span className="font-semibold text-[#fde68a]">{ledger.totalPending} VP</span></p></section><section className="mx-auto mt-6 grid max-w-7xl gap-6 md:grid-cols-12"><div className="rounded-xl border border-[#262932] bg-[#16181d] p-6 md:col-span-8"><p className="text-xs font-semibold text-[#9ca3af]">TOTAL VIGIL POINTS</p><p className="mt-4 text-5xl font-semibold text-[#eab308]">{ledger.totalConfirmed}</p><p className="mt-2 font-semibold text-[#eab308]">VP</p><p className="mt-5 max-w-xl text-sm leading-6 text-[#c7c4d7]">{ledger.disclaimer}</p></div><div className="rounded-xl border border-[#262932] bg-[#16181d] p-6 md:col-span-4"><h2 className="text-xl font-semibold text-[#f9fafb]">Points Breakdown</h2><div className="mt-6 space-y-4"><Row label="已确认" value={`${ledger.totalConfirmed} VP`} /><Row label="待确认" value={`${ledger.totalPending} VP`} tone="text-[#fde68a]" /><Row label="已拒绝" value={`${ledger.totalRejected} VP`} /></div></div><section className="md:col-span-7"><h2 className="mb-4 text-xl font-semibold text-[#f9fafb]">任务与活动</h2><div className="space-y-3">{rules.map(([type, rule]) => <div key={type} className="flex items-center justify-between gap-4 rounded-xl border border-[#262932] bg-[#16181d] p-4"><div><p className="font-semibold text-[#f9fafb]">{type}</p><p className="mt-1 text-sm text-[#c7c4d7]">{rule.reason}</p></div><span className="font-semibold text-[#eab308]">+{rule.points} VP</span></div>)}</div></section><section className="md:col-span-5"><h2 className="mb-4 text-xl font-semibold text-[#f9fafb]">VP 状态说明</h2><div className="rounded-xl border border-[#262932] bg-[#16181d] p-5 text-sm leading-7 text-[#c7c4d7]"><p>已确认 VP 仅用于记录产品贡献。</p><p className="mt-3">待确认 VP 不展示为可用余额，可能因反作弊或事件校验而变化。</p><p className="mt-3 text-[#fde68a]">VP 不等于未来 token，也不承诺固定兑换。</p></div></section></section><MobileNav active="points" /></main>;
}

function Row({ label, value, tone = "text-[#f9fafb]" }: { label: string; value: string; tone?: string }) { return <div className="flex justify-between border-b border-[#262932] pb-3"><span className="text-[#9ca3af]">{label}</span><span className={`font-semibold ${tone}`}>{value}</span></div>; }
