import Link from "next/link";
import { buildMockWalletHealthReport } from "@chainvigil/risk-core";
import { MobileNav } from "../../ui/mobile-nav";

const color = { HIGH: "#ef4444", MEDIUM: "#f59e0b", LOW: "#10b981", UNKNOWN: "#9ca3af" } as const;

export default function ApprovalsPage() {
  const report = buildMockWalletHealthReport({ address: "0x1111111111111111111111111111111111111110" });
  return <main className="min-h-screen bg-[#0a0b0f] pb-24 text-[#e4e1ed] md:pb-10"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#262932] bg-[#0a0b0f]/95 px-5 backdrop-blur md:px-8"><Link href="/" className="font-semibold text-[#f9fafb]">ChainVigil AI</Link><Link href="/wallet-check" className="text-sm text-[#c7c4d7]">钱包体检</Link></header><div className="mx-auto max-w-6xl px-5 py-9 md:px-8"><section><p className="text-sm font-semibold text-[#c0c1ff]">Mock read-only scan</p><h1 className="mt-3 text-3xl font-semibold text-[#f9fafb] md:text-5xl">授权扫描</h1><p className="mt-4 max-w-2xl leading-7 text-[#9ca3af]">展示 spender、授权范围和风险理由。V0 不连接钱包、不发起撤销交易，也不请求签名。</p></section><section className="mt-8 grid gap-4 md:grid-cols-4">{[["体检分", report.summary.score],["高危授权", report.summary.highRiskApprovals],["无限授权", report.summary.infiniteApprovals],["可疑资产", report.summary.suspiciousTokens]].map(([label, value]) => <article key={String(label)} className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><p className="text-sm text-[#9ca3af]">{label}</p><p className="mt-3 text-2xl font-semibold text-[#f9fafb]">{value}</p></article>)}</section><section className="mt-8 space-y-4">{report.approvals.map((approval) => <article key={approval.id} className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold text-[#f9fafb]">{approval.assetSymbol}</h2><span className="rounded px-2 py-1 text-xs font-semibold" style={{ backgroundColor: `${color[approval.riskLevel]}1a`, color: color[approval.riskLevel] }}>{approval.riskLevel}</span></div><p className="mt-2 text-sm text-[#9ca3af]">{approval.spenderLabel} · {approval.assetType}</p><p className="mt-2 break-all font-mono text-xs text-[#c7c4d7]">{approval.spenderAddress}</p></div><span className="rounded-lg border border-[#464554] px-3 py-2 text-sm text-[#c7c4d7]">{approval.allowanceLabel}</span></div><div className="mt-5 grid gap-4 border-t border-[#262932] pt-4 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-[#9ca3af]">风险理由</p><div className="mt-2 flex flex-wrap gap-2">{approval.riskReasons.map((reason) => <span key={reason} className="rounded bg-[#292932] px-2 py-1 text-xs text-[#c7c4d7]">{reason}</span>)}</div></div><div><p className="text-xs font-semibold uppercase text-[#9ca3af]">建议</p><p className="mt-2 text-sm leading-6 text-[#c0c1ff]">{approval.recommendedAction}</p></div></div></article>)}</section><section className="mt-8 rounded-xl border border-[#262932] bg-[#1b1b23] p-5"><p className="text-sm leading-7 text-[#9ca3af]">演示数据使用 mock 地址。真实撤销授权必须由用户核对 spender、资产、额度和 gas 后，在钱包中自行签名确认。</p><Link href="/wallet-check" className="mt-4 inline-block rounded-lg bg-[#c0c1ff] px-4 py-3 text-sm font-semibold text-[#1000a9]">查看只读体检</Link></section></div><MobileNav active="wallet" /></main>;
}
