import Link from "next/link";
import { listMockWalletWatchlist } from "@chainvigil/risk-core";
import { MobileNav } from "../../ui/mobile-nav";

const statusLabel = { checked: "已体检", pending_check: "待检查", watching: "监控中" } as const;

export default function WalletsPage() {
  const wallets = listMockWalletWatchlist("");
  return <main className="min-h-screen bg-[#0a0b0f] pb-24 text-[#e4e1ed] md:pb-10"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#262932] bg-[#0a0b0f]/95 px-5 backdrop-blur md:px-8"><Link href="/" className="font-semibold text-[#f9fafb]">ChainVigil AI</Link><Link href="/wallet-check" className="text-sm text-[#c0c1ff]">体检钱包</Link></header><div className="mx-auto max-w-6xl px-5 py-9 md:px-8"><section><p className="text-sm font-semibold text-[#c0c1ff]">Read-only watchlist</p><h1 className="mt-3 text-3xl font-semibold text-[#f9fafb] md:text-5xl">我的钱包</h1><p className="mt-4 max-w-2xl leading-7 text-[#9ca3af]">V0 只展示共享 mock watchlist，不要求连接钱包、不请求签名，也不会读取私钥或助记词。</p></section><section className="mt-8 grid gap-4 md:grid-cols-3">{[["钱包样例", wallets.length],["已体检", wallets.filter((wallet) => wallet.status === "checked").length],["待处理高危授权", wallets.reduce((sum, wallet) => sum + (wallet.highRiskApprovals ?? 0), 0)]].map(([label, value]) => <article key={String(label)} className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><p className="text-sm text-[#9ca3af]">{label}</p><p className="mt-3 text-2xl font-semibold text-[#f9fafb]">{value}</p></article>)}</section><section className="mt-8 space-y-4">{wallets.map((wallet) => <article key={wallet.address} className="rounded-xl border border-[#262932] bg-[#16181d] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold text-[#f9fafb]">{wallet.label}</h2><span className="rounded bg-[#292932] px-2 py-1 text-xs text-[#c7c4d7]">{wallet.chain}</span></div><p className="mt-2 break-all font-mono text-xs text-[#c7c4d7]">{wallet.address}</p></div><span className="rounded-lg border border-[#464554] px-3 py-2 text-sm text-[#c7c4d7]">{statusLabel[wallet.status]}</span></div><p className="mt-4 text-sm text-[#c0c1ff]">{wallet.summaryLabel}</p><p className="mt-2 leading-7 text-[#9ca3af]">{wallet.note}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[#262932] pt-4"><span className="text-sm text-[#9ca3af]">高危授权 {wallet.highRiskApprovals ?? "待查"}</span><Link href={wallet.reportUrl} className="rounded-lg border border-[#464554] bg-[#1f1f27] px-4 py-2 text-sm font-semibold text-[#f9fafb]">查看只读体检</Link></div></article>)}</section></div><MobileNav active="wallet" /></main>;
}
